In [1]:
import numpy as np

In [2]:
# 1D Array
arr1 = np.array([1, 2, 3, 4])
print("1D Array:", arr1)

# 2D Array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", arr2)

# 3D Array
arr3 = np.array([[[1,2],[3,4]], [[5,6],[7,8]]])
print("3D Array:\n", arr3)

1D Array: [1 2 3 4]
2D Array:
 [[1 2 3]
 [4 5 6]]
3D Array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [3]:
arr = np.array([10, 20, 30, 40, 50])

# Indexing
print("First Element:", arr[0])

# Slicing
print("Slice:", arr[1:4])

# Reshaping
arr_reshape = np.array([1,2,3,4,5,6])
reshaped = arr_reshape.reshape(2,3)

print("Reshaped Array:\n", reshaped)

First Element: 10
Slice: [20 30 40]
Reshaped Array:
 [[1 2 3]
 [4 5 6]]


In [4]:
a = np.array([1,2,3])
b = np.array([4,5,6])

# Element-wise operations
print("Addition:", a + b)
print("Multiplication:", a * b)

# Broadcasting
c = np.array([10])
print("Broadcasting:", a + c)

Addition: [5 7 9]
Multiplication: [ 4 10 18]
Broadcasting: [11 12 13]


In [5]:
data = np.array([10, 20, 30, 40, 50])

print("Mean:", np.mean(data))
print("Median:", np.median(data))
print("Standard Deviation:", np.std(data))
print("Percentile (25%):", np.percentile(data, 25))

Mean: 30.0
Median: 30.0
Standard Deviation: 14.142135623730951
Percentile (25%): 20.0


In [6]:
A = np.array([[1,2], [3,4]])
B = np.array([[5,6], [7,8]])

# Dot Product
print("Dot Product:\n", np.dot(A, B))

# Matrix Multiplication
print("Matrix Multiplication:\n", A @ B)

Dot Product:
 [[19 22]
 [43 50]]
Matrix Multiplication:
 [[19 22]
 [43 50]]


In [7]:
# Random numbers
rand_nums = np.random.rand(5)
print("Random Numbers:", rand_nums)

# Random integers
rand_ints = np.random.randint(1, 100, size=5)
print("Random Integers:", rand_ints)

# Random sample from array
data = np.array([10,20,30,40,50])
sample = np.random.choice(data, size=3)

print("Random Sample:", sample)

Random Numbers: [0.81876381 0.15568116 0.06106687 0.77841472 0.55874748]
Random Integers: [87 25 38 29 89]
Random Sample: [50 40 10]


In [9]:
# Example stock prices
prices = np.array([100, 102, 101, 105, 110, 108])

# Daily returns
returns = np.diff(prices)

print("Prices:", prices)
print("Daily Changes:", returns)

print("Average Price:", np.mean(prices))
print("Max Price:", np.max(prices))
print("Min Price:", np.min(prices))

Prices: [100 102 101 105 110 108]
Daily Changes: [ 2 -1  4  5 -2]
Average Price: 104.33333333333333
Max Price: 110
Min Price: 100
